/**
 * Product on Shelf — Apps Script entry point.
 *
 * index.html is a thin "include manifest" (generated by build.py from src/ + MANIFEST):
 * a list of <?!= include('src/...') ?> scriptlets that stitch the source partials back
 * together in load order. We evaluate it as a template so those includes run.
 */
function doGet() {
  var t = HtmlService.createTemplateFromFile('index');
  t.PRICING_JSON = posPricingJson_();   // injected into the bootstrap <script> (see ReadPath.gs + build.py)
  t.USER_JSON = userContextJson_();     // RBAC: window.USER = { email, role } (see Auth.gs + build.py)
  return t.evaluate()
    .setTitle('Product on Shelf')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

/**
 * Inline a source partial's content into the index template.
 * Called by every <?!= include('src/...') ?> line in index.html.
 */
function include(filename) {
  return HtmlService.createHtmlOutputFromFile(filename).getContent();
}
